// <auto-generated />
using System;
using MicroServicioVentas.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroServicioVentas.Migrations
{
    [DbContext(typeof(MicroServicioVentasContext))]
    [Migration("20251117014056_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCliente");

                    b.HasIndex("Ci")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Correo", b =>
                {
                    b.Property<int>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCorreo"));

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.HasKey("IdCorreo");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.ToTable("Correo");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoIdPedido")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("IdDetallePedido");

                    b.HasIndex("PedidoIdPedido");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDireccion"));

                    b.Property<int?>("IdDependiente")
                        .HasColumnType("integer");

                    b.Property<int>("IdPais")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDireccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdPais");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPais"));

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaPedido")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<int>("IdPromocion")
                        .HasColumnType("integer");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdPromocion");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("IdProducto");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPromocion"));

                    b.Property<string>("CodigoPromocion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombrePromocion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPromocion");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenta"));

                    b.Property<int>("CodigoTransaccion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("PedidoIdPedido")
                        .HasColumnType("integer");

                    b.HasKey("IdVenta");

                    b.HasIndex("CodigoTransaccion")
                        .IsUnique();

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.VentaBaja", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<bool>("CampanaCreada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("integer");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAlerta");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("VentaBaja");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Correo", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Cliente", "Cliente")
                        .WithMany("Correos")
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.DetallePedido", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("PedidoIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroServicioVentas.Core.Entity.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Direccion", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Pedido", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroServicioVentas.Core.Entity.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("IdDireccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroServicioVentas.Core.Entity.Promocion", "Promocion")
                        .WithMany()
                        .HasForeignKey("IdPromocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Direccion");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Venta", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.VentaBaja", b =>
                {
                    b.HasOne("MicroServicioVentas.Core.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Cliente", b =>
                {
                    b.Navigation("Correos");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("MicroServicioVentas.Core.Entity.Producto", b =>
                {
                    b.Navigation("DetallesPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
